---
- name: Open MongoDB port on VM2
  firewalld:
    port: 27017/tcp
    permanent: yes
    state: enabled
  when: inventory_hostname == "vm2"

- name: Open MongoDB port on VM3
  firewalld:
    port: 27017/tcp
    permanent: yes
    state: enabled
  when: inventory_hostname == "vm3"

- name: Open MongoDB port on VM4
  firewalld:
    port: 27017/tcp
    permanent: yes
    state: enabled
  when: inventory_hostname == "vm4"

- name: Open FastAPI port on VM3
  firewalld:
    port: 8000/tcp
    permanent: yes
    state: enabled
  when: inventory_hostname == "vm3"

- name: Reload firewalld
  command: firewall-cmd --reload
