apiVersion: v1
kind: Pod
metadata:
  name: python-mongo-client
spec:
  nodeSelector:
    kubernetes.io/hostname: vm4
  containers:
    - name: python-mongo-client
      image: pingumaniac/pymongo:main  # Replace with your image name
      # leesuh/pymongo:latest
      imagePullPolicy: Always
      command: ["python", "/app/vm1/app/test.py"] # not /app/test.py
      # command: ["bash", "/app/vm1/app/run_tests.sh"]
      # Not needed if scripts and dependencies are already in the Docker image.
      volumeMounts:
        - name: app-volume
          mountPath: /app/vm1/app
  restartPolicy: Never # Always?
  # Can be omitted unless you plan to use dynamic or shared storage.
  volumes:
    - name: app-volume
      emptyDir: {}
