---
- name: Install Kubernetes and Set Up Cluster
  hosts: all
  become: true
  tasks:
    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - curl
        state: present
        update_cache: yes

    - name: Add Kubernetes APT key
      command: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

    - name: Add Kubernetes repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb https://apt.kubernetes.io/ kubernetes-xenial main"

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages at current version
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
        allow_unauthenticated: yes

- name: Set Up Kubernetes Master (VM1)
  hosts: VM1
  become: true
  tasks:
    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: init_output

    - name: Save kubeconfig for user
      command: >
        mkdir -p $HOME/.kube &&
        cp /etc/kubernetes/admin.conf $HOME/.kube/config &&
        chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Display join command for worker nodes
      debug:
        msg: "{{ init_output.stdout_lines | select('search', 'kubeadm join') | list }}"

- name: Join Kubernetes Cluster (VM2, VM3, VM4)
  hosts: VM2,VM3,VM4
  become: true
  tasks:
    - name: Join Kubernetes cluster
      command: "{{ hostvars['VM1']['init_output.stdout_lines'] | select('search', 'kubeadm join') | list }}"
